version: "3.9"
services:
  kassenbuch:
    image: tsgames/mini-kassenbuch:latest
    build: .
    ports:
      - "8080:80"
    volumes:
        - data:/var/www/html/data
        - ./src/:/var/www/html/src
        - ./public/:/var/www/html/public
        - ./templates/:/var/www/html/templates
        - ./vendor/:/var/www/html/vendor

volumes:
  data: