apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mini-kassenbuch.fullname" . }}
  labels:
    {{- include "mini-kassenbuch.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "mini-kassenbuch.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mini-kassenbuch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mini-kassenbuch.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
          - name: data
            mountPath: {{ .Values.persistence.mountPath }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode }}
      {{- if .Values.persistence.storageClassName }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}

---

kind: Service
apiVersion: v1
metadata:
  name: mini-kassenbuch-service
spec:
  selector:
    app: mini-kassenbuch
  ports:
    - port: 80 # Default port for image

---
apiVersion: networking.k8s.io/v1
kind: Ingress
annotations:
metadata:
  name: mini-kassenbuch-ingress
spec:
  #ingressClassName: nginx # change this to your Ingressclass you have created in your cluster
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: mini-kassenbuch-service
            port:
              number: 80
        path: /
        pathType: Prefix